### PR TITLE
[FEAT] Add script to automate installation of supagen CLI into Windows OS

### PR DESCRIPTION
**Pull request by Prakharpan-dey**
## Related Issue
- [#27 ](https://github.com/supagen/supagen/issues/27) 
- For now, there is no script for install supagen CLI into Windows OS.
  We have to download, extract, and configure it manually.

## Evidence

https://github.com/user-attachments/assets/70b584a2-a2a4-491c-8a3b-e631e0896e44

## Checklist
- [x] I have read the [contributing guidelines](https://github.com/supagen/supagen/blob/main/CONTRIBUTING.md).
- [x] The code follows the project's style guidelines.
- [x] I have tested my changes and ensured they work as expected.
- [ ] I have included tests for new functionality.
- [ ] Documentation has been updated, if applicable.

## Additional Notes
**Tasks Done:**
- [x] Create installation script for windows in the folder:
       https://github.com/supagen/supagen/tree/main/scripts
- [x] Test the script already running properly, with attach some evidence into your pull request

### CODE REVIEW

**Comment by andikadeveloper** [comment]
It looks great @Prakharpan-dey! Thanks for your PR.

Feedback:

- [x] Use proper commit message. See the commit message convention in [CONTRIBUTING.md](https://github.com/supagen/supagen/blob/main/CONTRIBUTING.md#commit-messages) 
- [x] Update the documentation of how to install `supagen` CLI in windows section [README.md](https://github.com/supagen/supagen/blob/main/README.md#windows)
- [x] I just tried to run your script, but I got an error. Then, I fixed the error with this [Stackoverflow](https://stackoverflow.com/questions/64633727/how-to-fix-running-scripts-is-disabled-on-this-system). I think, we should update the documentation of how to fix the error in `README.md` or can we add the command to fix the issue in the `install.ps1` script also?
telegram-cloud-photo-size-5-6069106402535784454-y
- [x] And the last, can we the show `supagen` ASCII in the last, after `supagen` has been installed. So, the behaviour will look the same like `install.sh` script

https://github.com/user-attachments/assets/06eb1d15-5b6a-4fe8-a9f5-91a3df6de55a

**Comment by andikadeveloper** [comment]
Hey @Prakharpan-dey, nice changes for the feedbacks, thanks.
But, I don't see any changes in the commit messages. Please use proper commit message.
image

You can see the example in **Commit Messages** section [Here](https://github.com/supagen/supagen/blob/main/CONTRIBUTING.md#commit-messages)

Because you already push the changes, you can do this in the following way:
1. Run `git reset --soft` to the commit before your changes
2. Commit your changes using proper commit message
3. Push your changes to this branch with `--force` flag

Note:
We will approved this PR until the commit message has been updated.

**Comment by Prakharpan-dey** [comment]
@andikadeveloper Hey i just updated the commit messages according to the convention. Take a look and let me know if there are any more changes to be done.

**Comment by andikadeveloper** [comment]
Nice @Prakharpan-dey, but It will more look good, if you add a space after the colon ":" and make the first letter of the commit message to become lower case.

Like this:
`feat(27): add script to automate installation of supagen CLI into Windows OS`

**Comment by Prakharpan-dey** [comment]
@andikadeveloper done

**Review by andikadeveloper — APPROVED** [review]

**Comment by andikadeveloper** [comment]
@Prakharpan-dey Looks great! Could you add a comment into this issue [#27](https://github.com/supagen/supagen/issues/27) So, I can assign the issue to you

**Review by fathrezza146 — APPROVED** [review]

**Review by davidsarono — APPROVED** [review]

**Pull request merged**
